### ISSUE TITLE
Unfinished Nex file from GARD

### ISSUE THREAD

**Issue by Daniyalprime** [veg/hyphy#1565]
I tried to run MEME in datamonkey web server. But it is giving me the error mentioned below. I looked into the nex file ,i think it is not finished.
Ticket Number : 2371889.new-silverback

MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:16801] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15

**Comment by spond** [comment]
Dear @Daniyalprime,

Can you please provide the Datamonkey URL (not the ticket number)?

Best,
Sergei

**Comment by Daniyalprime** [comment]
Sure.Thank you for replying.
https://www.datamonkey.org/gard/63d7969ec82f520f6a32b53a

**Comment by stevenweaver** [comment]
Dear @Daniyalprime, 

It appears that my failsafe for this situation worked, and that the page is now reporting your results. 

Can you please confirm that your issue is resolved?

Best,
Steven

**Comment by Daniyalprime** [comment]
When I upload the partition file from GARD into MEME, the issue is still happening.@stevenweaver

Standard Error Message
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[n6:86629] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:86629] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:86629] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:86629] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:86629] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:86629] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:86629] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
[n6:86629] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 1741
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15
