### ISSUE TITLE
hyphy errors out intermittently in AA+G methods w/ likelihood issue 

### ISSUE THREAD

**Issue by sjspielman** [veg/hyphy#689]
Hi @spond, 

I mentioned to you the other day that I’m having weird issues with the protein fitter intermittently hyphy issues. Turns out this issue may be broader, and possibly an AA model issue, since I've only encountered this w/ protfitter and LEISR: For **rate variation** (Gamma) models on certain datasets, LEISR is failing with an error along these lines:

`Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-2.12454e+06] does not match the last recorded LF maximum [-125991]`

I had seen a message like this, I now recall, in the stdout for protein fitter failed runs. 

 I’ve attached an example that you can test w/ LEISR.  [1HV9_A.fna.txt](https://github.com/veg/hyphy/files/1438864/1HV9_A.fna.txt)

+ I am only able to reproduce on silverback, NOT locally on my machine. Silverback was compiled w/ gcc6, and I use gcc7.
+ Running here only w/ MP

You can run the attached w/ these options (in beta branch):
0: specifiy alignment
1: "y" to accept tree
2: "Protein"
3: "WAG"
4: "Gamma"

**Comment by sjspielman** [comment]
Here's another example if you need one, due to stochasticity. 
[EXAMPLE.txt](https://github.com/veg/hyphy/files/1438869/EXAMPLE.txt)

**Comment by spond** [comment]
Dear @sjspielman,

This should now be resolved via commit a524547 to the `beta` branch. The issue had to do with how some phases of the optimization (calls to `ConjugateGradientDescent` when convergence was too slow) would not update an internal "current maximum" tracking variable, which is meant to act as a checkpoint to catch internal errors. This (I think) has now been resolved. I don't think the issue was specific to +Gamma, but please confirm that the odd behavior has been dealt with.

Best,
Sergei

**Comment by sjspielman** [comment]
Hi @spond , 

I still get the `ConjugateGradientDescent` errors, unfortunately... Any others ideas?

-Stephanie

**Comment by spond** [comment]
Dear @sjspielman,

This is with the `beta` branch? On the cluster or on your local machine? 

Best,
Sergei

**Comment by sjspielman** [comment]
Can officially confirm: Happens on `beta` branch, on both local machine and cluster. Full example of failed run attached.
Note, even so, there are no warnings seen w/ small dataset.
[conjugate.zip](https://github.com/veg/hyphy/files/1447273/conjugate.zip)

**Comment by spond** [comment]
Dear @sjspielman,

I can't break it on my LLVM compilation. Could you please set `VERBOSITY_LEVEL=100;` and then paste in the console transcript up to the point where the code errors?

Best,
Sergei

**Comment by sjspielman** [comment]
Attached here. Note that this was the call: 
`/Users/sjspielman/hyphy/HYPHYMP LIBPATH=/Users/sjspielman/hyphy/res /Users/sjspielman/hyphy/res/TemplateBatchFiles/LEISR.bf /Users/sjspielman/Research/leisr_validation/compare_models/enzyme_data/1A8S_A.fna y Protein JC69 Gamma`
[console.txt](https://github.com/veg/hyphy/files/1447316/console.txt)

**Comment by spond** [comment]
Dear @sjspielman,

Aha -- that's a different route to the error compared to what I fixed; something I can reproduce and work with.

Best,
Sergei

**Comment by spond** [comment]
Dear @sjspielman,

OK, try the fix in dbd32ac. This was a very obscure bug that was triggered only for very poorly fitting sites (that needed to be scaled a lot to avoid underflow). I am very glad you helped me track it down.

Best,
Sergei

**Comment by sjspielman** [comment]
Hi @spond, 

Everything is running now as expected, so issue appears fixed! Thanks!

-Stephanie

**Comment by spond** [comment]
Dear @sjspielman,

No, thank **you**. I have known for some lurking issues for sometime, but could never pin them down, and you helped me do it!!

Best,
Sergei
