### ISSUE TITLE
Internal error in _LikelihoodFunction

### ISSUE THREAD

**Issue by franzileo** [veg/hyphy#703]
Dear developers,

when performing RELAX the same error as issued here https://github.com/veg/hyphy/issues/294 occured. However when I comment the mentioned lines in likefunc.cpp out, the error remains. 
I searched my whole hyphy directory for another occurrence of  
'Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values' 
but can't find anything.
Do you have any idea what could be the problem here?

Thanks a lot in advance!
Best,
Franziska

**Comment by spond** [comment]
Dear @franzileo,

This issue has been resolved in release 2.3.7.

Best,
Sergei

**Comment by SouthernCD** [comment]
When I use v2.3.7 to run RELAX, I still get ConjugateGradientDescent error in some case ...

`### Fitting the general descriptive (separate k per branch) model
Error:

Master node received an error:Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-4e+100] does not match the last recorded LF maximum [20341.2]
`

**Comment by spond** [comment]
Dear @SouthernCD,

Would you be able to send me the input file and analysis settings for RELAX that trigger this error? I'd like to confirm it and fix it  if confirmed. 

Best,
Sergei

**Comment by SouthernCD** [comment]
Dear Sergei,

 

Thank you very much for your reply. 

 

My job is a big analysis for about 10000 gene orthogroups, I wish get k value for every branch, but about 2000 group will get the error about ConjugateGradientDescent.

 

Attachment is one of my error orthogroups data including input file and analysis setting in a bf file.

 

Thanks for you debug, and if there are anything I can do, please let me know  😊

 

SouthernCD

 

发件人: bounces+848413-766c-xuyuxing14=mails.ucas.ac.cn@sgmail.github.com [mailto:bounces+848413-766c-xuyuxing14=mails.ucas.ac.cn@sgmail.github.com] 代表 Sergei Pond
发送时间: Thursday, November 30, 2017 01:45
收件人: veg/hyphy <hyphy@noreply.github.com>
抄送: Yuxing Xu <xuyuxing14@mails.ucas.ac.cn>; Mention <mention@noreply.github.com>
主题: Re: [veg/hyphy] Internal error in _LikelihoodFunction (#703)

 

Dear @SouthernCD <https://github.com/southerncd> ,

Would you be able to send me the input file and analysis settings for RELAX that trigger this error? I'd like to confirm it and fix it if confirmed.

Best,
Sergei

**Comment by SouthernCD** [comment]
发件人: bounces+848413-766c-xuyuxing14=mails.ucas.ac.cn@sgmail.github.com [mailto:bounces+848413-766c-xuyuxing14=mails.ucas.ac.cn@sgmail.github.com] 代表 Sergei Pond
发送时间: Thursday, November 30, 2017 01:45
收件人: veg/hyphy <hyphy@noreply.github.com>
抄送: Yuxing Xu <xuyuxing14@mails.ucas.ac.cn>; Mention <mention@noreply.github.com>
主题: Re: [veg/hyphy] Internal error in _LikelihoodFunction (#703)

 

Dear @SouthernCD <https://github.com/southerncd> ,

Would you be able to send me the input file and analysis settings for RELAX that trigger this error? I'd like to confirm it and fix it if confirmed.

Best,
Sergei

**Comment by SouthernCD** [comment]
I have send a mail for you ,thanks again @spond

**Comment by franzileo** [comment]
Dear Developers,

I have another problem corresponding to this. I get a similar error but this time when running MEME.
"Internal error in  _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration"
I am only getting this error in some cases using version 2.3.7 of hyphy, in version 2.3.4 it never occured.
Now I already out-commented the corresponding line in /src/core/likefunc.cpp, like this:
/* if (maxSoFar < initialValue && !CheckEqual (maxSoFar, initialValue)) {
          WarnError (_String ("Internal error in  _LikelihoodFunction::GradientLocateTheBump: in the Brent loop iteration ") & long(outcome) & ". " & maxSoFar & " / " & initialValue & ".\n");// & _String ((_String*)brentHistory.toStr()));
          return;
        } */
However, the error is still occuring and I don't have any glue where it comes from.
Do you have any idea? Is there some other file where this is implemented.

I also added  fprintf ("yes hyphy is using this likefunc.cpp file")  to the likefunc.cpp file and the print does not occur in the terminal when so running MEME so it seems for some reason this file is not used..? Is that right? Is there any other possibility to find out which likefunc.cpp file is actually used?

Thanks a lot in advance!
Best, Franziska

**Comment by spond** [comment]
Dear @franzileo,

Have you rebuilt the binary from source using `make MP` and then `make install`?\

Could you also send me a data file which cause the error to crop up in 2.3.7? I'd like to track it down and resolve it more systematically than simply ignoring error conditions :? 

Best,
Sergei

**Comment by spond** [comment]
Dear @SouthernCD,

I just pushed a commit to the `beta` branch which should resolve your RELAX issue. It had to do with numerical instability of matrix exponentiation when both &omega; and k were sufficiently large, making &omega;<sup>k</sup> very large (e.g. 10<sup>20</sup>).

Best,
Sergei

**Comment by SouthernCD** [comment]
Dead @spond,

This is work well, I will redo it for all my jobs ~~, thank you very much~~

Best,
Yuxing

**Comment by spond** [comment]
Dear @franzileo,

I was able to track your issue down to a few sites that had data like

```
NNN
---
---
...
```

HyPhy was throwing an error because the log-likelihood for such sites **could** evaluate to a positive number due to numerical error (just a very small one).

I implemented a simple fix in the `beta` branch. You can try it by 

```
$git clone https://github.com/veg/hyphy.git
$git checkout beta
$cmake ./
$make install
```

Best,
Sergei
